# Generated by Django 5.2

from django.db import migrations

def create_default_categories(apps, schema_editor):
    """
    Create default supplier categories
    """
    SupplierCategory = apps.get_model('suppliers', 'SupplierCategory')
    
    categories_to_create = [
        {"name": "Construction", "description": "Building, civil engineering, and infrastructure services"},
        {"name": "IT Services", "description": "Software development, network services, and IT infrastructure"},
        {"name": "Consultation", "description": "Professional consulting services across various domains"}
    ]
    
    for category_data in categories_to_create:
        SupplierCategory.objects.get_or_create(
            name=category_data["name"],
            defaults={"description": category_data["description"]}
        )

def remove_default_categories(apps, schema_editor):
    """
    Remove the default categories (for rollback)
    """
    SupplierCategory = apps.get_model('suppliers', 'SupplierCategory')
    
    category_names = [
        "Construction",
        "IT Services",
        "Consultation"
    ]
    
    SupplierCategory.objects.filter(name__in=category_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),  # Make sure this matches your initial migration
    ]

    operations = [
        migrations.RunPython(create_default_categories, remove_default_categories),
    ]