# Generated by Django 5.2 on 2025-04-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='termination_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
